name: kl_cnc_controller
description: KL CNC Controller - GRBL USB & WiFi Serial
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # USB Serial OTG
  usb_serial: ^0.4.5

  # WiFi / TCP Socket
  network_info_plus: ^4.1.0

  # State management
  provider: ^6.1.1

  # Local storage (settings)
  shared_preferences: ^2.2.2

  # File picker (load .nc/.gcode files)
  file_picker: ^6.1.1

  # Permission handling
  permission_handler: ^11.1.0

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
